### ISSUE TITLE
不支持 https 的认证服务器

### ISSUE THREAD

**Issue by SadPencil** [zu1k/sdusrun#1]
例如中科院计算所，是可以直接用sdunetd的，你的移植版本写死了http

**Comment by zu1k** [comment]
仅打算支持sdu，为了尽量减少二进制大小，去除了不必要的tls支持

如有需要，可自行编译开启tls支持的版本

**Comment by SadPencil** [comment]
> 
> 
> 仅打算支持sdu，为了尽量减少二进制大小，去除了不必要的tls支持
> 
> 如有需要，可自行编译开启tls支持的版本
> 
> > 你的移植版本
> 
> 不是移植哦，与你的实现方式完全不同，没有用任何js vm

你的 issue 标题叫 `A new rust port`，port 一词即为移植，我按你的标题说的

**Comment by zu1k** [comment]
> 你的 issue 标题叫 `A new rust port`，port 一词即为移植，我按你的标题说的

确实，这是我的锅😂
