### ISSUE TITLE
version for router？

### ISSUE THREAD

**Issue by Xchuantangfeng** [zu1k/sdusrun#12]
Hello！
Is there any available version for a router which was installed a openwrt system？thanks.

**Comment by zu1k** [comment]
just select the right architecture.
no luci ui

**Comment by Xchuantangfeng** [comment]
> just select the right architecture. no luci ui

but there are some problems，can we communicate in Chinese for more details?

**Comment by zu1k** [comment]
😂可以

**Comment by Xchuantangfeng** [comment]
> joy可以

作者你好。
目前我给路由器刷了openwrt，学校校园网认证采用深澜web认证，我想让路由器在每次开机之后就能自动运行认证脚本，请问我该怎么做呢？

**Comment by zu1k** [comment]
整个systemd开机自启的服务
