### ISSUE TITLE
what is NIC name？

### ISSUE THREAD

**Issue by hotwa** [zu1k/sdusrun#14]

**Comment by hotwa** [comment]
如何填写 NIC name 参数

**Comment by hotwa** [comment]
网卡名称？在windows如何查看？

**Comment by zu1k** [comment]
其实我是不建议在 Windows 下用这个功能的，这本身是给多拨准备的，而多拨一般用在 linux 下比较方便。

windows 下网卡名是个 UUID，在 0.5.1 版本下可以通过 `--select-ip` 查看

**Comment by hotwa** [comment]
MIPSel版本没有32位的，编译的是64好像



---Original---
From: ***@***.***&gt;
Date: Tue, May 17, 2022 11:29 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [zu1k/sdusrun] what is NIC name？ (Issue #14)




 
其实我是不建议在 Windows 下用这个功能的，这本身是给多拨准备的，而多拨一般用在 linux 下比较方便。
 
windows 下网卡名是个 UUID，在 0.5.1 版本下可以通过 --select-ip 查看

**Comment by zu1k** [comment]
如果有其他问题，请开新的 issue 提问。

mipsel 是 32 位的

```
$ file sdusrun-mipsel-unknown-linux-musl
sdusrun-mipsel-unknown-linux-musl: ELF 32-bit LSB shared object, MIPS, MIPS32 rel2 version 1 (SYSV), statically linked, no section header
```
