### ISSUE TITLE
Can not login

### ISSUE THREAD

**Issue by hotwa** [zu1k/sdusrun#16]
```shell
[root@Router ~]$ ./sdusrun-mipsel-unknown-linux-musl login -c config.json 
login user: User {
    username: "schoolcode@unicom",
    password: "pwd",
    ip: Some(
        "10.8.135.11",
    ),
    if_name: None,
}
ChallengeResponse {
    challenge: Some(
        "0e367f2a93c10d48caca8b91a78629fa3a81b9d93cee0db97eb53e5c31395273",
    ),
    client_ip: "10.8.135.11",
    ecode: I(
        0,
    ),
    error_msg: "",
    expire: Some(
        "60",
    ),
    online_ip: "10.8.135.11",
    res: "ok",
    srun_ver: "SRunCGIAuthIntfSvr V1.18 B20201030",
    st: 1652834055,
}
will try at most 1 times...
try 1/1: failed
PortalResponse {
    server_flag: 0,
    services_intf_server_ip: "",
    services_intf_server_port: "",
    access_token: "",
    checkout_date: 0,
    ecode: S(
        "",
    ),
    error: "login_error",
    error_msg: "Nas type not found.",
    client_ip: "10.8.135.11",
    online_ip: "10.8.135.11",
    real_name: "",
    remain_flux: 0,
    remain_times: 0,
    res: "login_error",
    srun_ver: "SRunCGIAuthIntfSvr V1.18 B20201030",
    suc_msg: "",
    sysver: "",
    username: "",
    wallet_balance: 0,
    st: 1652834055,
}
login user: User {
    username: "schoolcode@unicom",
    password: "passwd",
    ip: None,
    if_name: Some(
        "eth0.5",
    ),
}
ChallengeResponse {
    challenge: Some(
        "0e367f2a93c10d48caca8b91a78629fa3a81b9d93cee0db97eb53e5c31395273",
    ),
    client_ip: "10.8.135.11",
    ecode: I(
        0,
    ),
    error_msg: "",
    expire: Some(
        "57",
    ),
    online_ip: "10.8.135.11",
    res: "ok",
    srun_ver: "SRunCGIAuthIntfSvr V1.18 B20201030",
    st: 1652834058,
}
will try at most 1 times...
try 1/1: failed
PortalResponse {
    server_flag: 0,
    services_intf_server_ip: "",
    services_intf_server_port: "",
    access_token: "",
    checkout_date: 0,
    ecode: S(
        "",
    ),
    error: "login_error",
    error_msg: "Nas type not found.",
    client_ip: "10.8.135.11",
    online_ip: "10.8.135.11",
    real_name: "",
    remain_flux: 0,
    remain_times: 0,
    res: "login_error",
    srun_ver: "SRunCGIAuthIntfSvr V1.18 B20201030",
    suc_msg: "",
    sysver: "",
    username: "",
    wallet_balance: 0,
    st: 1652834058,
}
```

**Comment by hotwa** [comment]
config:

```json
{
    "server": "http://202.114.177.246",
    "strict_bind": false,
    "double_stack": false,
    "retry_delay": 3000,
    "retry_times": 1,
    "acid": 12,
    "os": "Windows",
    "name": "Windows 10",
    "users": [
        {
            "username": "scode@unicom",
            "password": "pwd",
            "ip": "10.8.135.11"
        },
        {
            "username": "scode@unicom",
            "password": "pwd",
            "if_name": "eth0.5"
        }
    ]
}
```

**Comment by hotwa** [comment]
"name": "Windows 10", 这里改成`Windows 98`, 就成功了。
反馈版本：SRunCGIAuthIntfSvr V1.18 B20201030
建议增加后台守护进程，一直ping 百度就行

**Comment by hotwa** [comment]
fiddler4 抓包登录接口：
```shell
GET http://202.114.177.246/cgi-bin/srun_portal?callback=jQuery112408245679912325432_1652837592439&action=login&username=hide%40cucc&password=%7B6b002c5aa4a5a18a34b87dcb1bd51d&os=Windows+95&name=Windows&double_stack=0&chksum=74c24bc634c38e71b53d04c252bf27495afaa889&info=%7BSRBX1%7D%2FiNdDE5JCF00ZhJCa4cd8Jtz9fEmV3VDGSfQGpwCbQ3l0u8bejbQElEcB7EOv%2BS%2FUlZ5R3PZtyl8V9QwyXtWS80AOzOzlwCgpvNqSuy9Et6h%2BykdkawtapeJdNuixrXy%2FUYEnklidOCPNvP5&ac_id=1&ip=10.8.220.20&n=200&type=1&_=1652837592442 HTTP/1.1
```

**Comment by hotwa** [comment]
```shell
login error: error sending request for url (http://202.114.177.246/cgi-bin/get_challenge?callback=sdu&username=102000549%40cucc&ip=10.8.135.11&_=1652837363): operation timed out
```
这里callback在rust哪里配置的

**Comment by hotwa** [comment]
```shell
GET http://202.114.177.246/cgi-bin/get_challenge?callback=jQuery112408245679912325432_1652837592439&username=schoolcode%40cucc&ip=10.8.220.20&_=1652837592441 HTTP/1.1
```
login error: error sending request for url (http://202.114.177.246/cgi-bin/get_challenge?callback=sdu&username=102000549%40cucc&ip=10.8.135.11&_=1652837363): operation timed out

**Comment by zu1k** [comment]
问题解决了吗？

**Comment by hotwa** [comment]
换了golang编译的版本，我学校后面抓包的有的参数不一样。中国联通是cucc，cmcc移动，ctcc电信，还有几个别的参数。get请求好像有点参数不一样，可能要加到config文件。不过rust版本编译体积是真小。语法不是特别熟，就不折腾改源码了，有空再研究研究



---Original---
From: ***@***.***&gt;
Date: Wed, May 18, 2022 13:02 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [zu1k/sdusrun] Can not login (Issue #16)




 
问题解决了吗？

**Comment by zu1k** [comment]
config.json 里面用户名改成 cucc 就行了

`"username": "user@cucc"`

**Comment by hotwa** [comment]
还有个user type问题，老师和学生的类型不同，不同学校也不同



---Original---
From: ***@***.***&gt;
Date: Wed, May 18, 2022 13:36 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [zu1k/sdusrun] Can not login (Issue #16)




 
config.json 里面用户名改成 cucc 就行了
 
"username": ***@***.***"

**Comment by hotwa** [comment]
感觉golang那个版本好，支持多网卡，不过好像有点bug。



---Original---
From: ***@***.***&gt;
Date: Wed, May 18, 2022 13:36 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [zu1k/sdusrun] Can not login (Issue #16)




 
config.json 里面用户名改成 cucc 就行了
 
"username": ***@***.***"

**Comment by zu1k** [comment]
是 `&type=1` 这个参数吗？我一直不知道这个参数是做啥用的

**Comment by hotwa** [comment]
是的，在我学校这边，老师和学生的不一样。
不同学校的标准好像也不一样



---Original---
From: ***@***.***&gt;
Date: Wed, May 18, 2022 13:41 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [zu1k/sdusrun] Can not login (Issue #16)




 
是 &amp;type=1 这个参数吗？我一直不知道这个参数是做啥用的

**Comment by hotwa** [comment]
最好抓一下包，不同学校的话。



---Original---
From: ***@***.***&gt;
Date: Wed, May 18, 2022 13:41 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [zu1k/sdusrun] Can not login (Issue #16)




 
是 &amp;type=1 这个参数吗？我一直不知道这个参数是做啥用的

**Comment by hotwa** [comment]
callback好像后面是个时间戳，随机的，任意参数好像都行，jquery_后面_时间戳，好像也可以任意，你的源码好像是sdu

**Comment by hotwa** [comment]
还有Windows 95有的是，98这个貌似也有影响

**Comment by zu1k** [comment]
callback 是 jsonp，应该可以任意

_ 时间戳 是为了绕过缓存，这个应该可有可无

windows 95 还是 98 这个可以在配置文件中修改

**Comment by hotwa** [comment]
哦，不是type，是ac_id=1这个，学生老师账号不一样

**Comment by zu1k** [comment]
ac_id 可以在配置文件中修改

**Comment by hotwa** [comment]
"meta": { //登录参数
    "n": "200",
    "type": "1",
    "acid": "5",
    "enc": "srun_bx1"
  },

**Comment by hotwa** [comment]
好的

**Comment by zu1k** [comment]
用最新的 0.5.3 版本

**Comment by hotwa** [comment]
acid改成1，Windows98改95登录上了



---Original---
From: ***@***.***&gt;
Date: Wed, May 18, 2022 13:57 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [zu1k/sdusrun] Can not login (Issue #16)




 
用最新的 0.5.3 版本

**Comment by zu1k** [comment]
ok，方便的话麻烦在 https://github.com/zu1k/sdusrun/discussions/8 记录一下你目前的 srun 版本号
